#!/bin/sh
set -eu
PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
PATCH="$PROJECT_DIR/patches/0001-add-dual-screen-browser-mode.patch"
UI_PATCH="$PROJECT_DIR/patches/0002-add-browser-chrome-and-home.patch"
SMOOTH_PATCH="$PROJECT_DIR/patches/0003-smooth-dual-screen-and-knowledge-home.patch"
grep -q 'DualScreenBrowserActivity' "$PATCH"
grep -q 'android:targetActivity=".dualscreen.DualScreenBrowserActivity"' "$PATCH"
grep -q 'launchDisplayId = secondary.displayId' "$PATCH"
grep -q 'components.core.geckoRuntime' "$PATCH"
grep -q 'logicalTop + if (isSecondary) 0 else geckoView.height' "$PATCH"
grep -q 'peer?.runOnUiThread' "$PATCH"
grep -q '双屏浏览器' "$UI_PATCH"
grep -q '输入网址或搜索内容' "$UI_PATCH"
grep -q 'www.baidu.com' "$UI_PATCH"
grep -q 'www.zhihu.com' "$UI_PATCH"
grep -q 'postOnAnimation' "$SMOOTH_PATCH"
grep -q 'programmaticTargetY' "$SMOOTH_PATCH"
grep -q 'TrackingProtectionPolicy.strict' "$SMOOTH_PATCH"
grep -q '百度百科' "$SMOOTH_PATCH"
grep -q '中国知网' "$SMOOTH_PATCH"
git -C "$PROJECT_DIR/browser" apply --check "$PATCH"
echo "DUAL SCREEN PATCH CHECK PASSED"
